version: '2'

services:
  db:
    image: mysql:latest
    container_name: db_server
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: wp_docker
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword

  example:
    depends_on:
      - db
    image: wpdiaries/wordpress-xdebug:5.7.2-php8.0-apache
    container_name: wp-web
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: adminpassword
      WORDPRESS_DB_NAME: wp_docker
      XDEBUG_CONFIG: client_host=docker.for.mac.host.internal
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./src:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: adminpassword
    ports:
      - 8081:80
    restart: always
