version: '2'

services:
  db:
    image: mysql:latest
    container_name: db_server
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword # any random string will do
      MYSQL_DATABASE: wp_docker # the name of your mysql database
      MYSQL_USER: admin # the name of the database user
      MYSQL_PASSWORD: adminpassword # the password of the mysql user

  example:
    depends_on:
      - db
    image: wordpress:php7.1 # we're using the image with php7.1
    container_name: wp-web
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: adminpassword
      WORDPRESS_DB_NAME: wp_docker
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./src:/var/www/html
